# Site Configuration for TaskNix.com
title: TaskNix
description: Expert productivity tool reviews and comparisons
baseurl: ""
url: "https://tasknix.com"

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:title/

# Default layouts
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Include these files
include:
  - _pages
  - _posts
  - assets
  - images

# Permalinks
permalink: /:title/

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass settings
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: development

# SEO settings
author: TaskNix Team
twitter:
  username: tasknix
  card: summary_large_image

# Keep files
keep_files:
  - .git
  - .svn