# Site Configuration for TaskNix.com
name: TaskNix
description: Expert reviews of productivity tools, software, and services
avatar: https://tasknix.com/images/tasknix-logo.png

# GitHub Pages specific settings
remote_theme: jekyll-theme-primer
github: [metadata]

# Site URL configuration
url: "https://tasknix.com"
baseurl: ""
timezone: America/New_York
future: false

# SEO Optimization
title: TaskNix | Productivity Tools Reviews & Comparisons
keywords: "productivity tools, software reviews, task management, time tracking"
twitter_username: tasknix
github_username: tasknix

# GitHub Pages approved plugins ONLY
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate  # Note: Using v1 instead of v2

# SEO Tag Configuration
jekyll-seo-tag:
  meta_tags:
    - name: "twitter:card"
      value: "summary_large_image"
    - name: "og:image"
      value: "/assets/default-social-image.jpg"

# Pagination (basic)
paginate: 10
paginate_path: "/reviews/page:num/"

# Feed Configuration
feed:
  path: feed.xml
  limit: 20

# Technical Configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - .idea
  - .vscode

# Collections
collections:
  productivity_tools:
    output: true
    permalink: /:collection/:name/
  categories:
    - project_management
    - note_taking
    - time_tracking
    - communication
    - file_sharing
    - automation
    - writing_software
    - scheduling_apps

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      affiliate_disclosure: true
      rating_system: true
      toc: true

# Social/Footer links
footer-links:
  twitter: tasknix
  github: tasknix/tasknix.github.io
  linkedin: company/tasknix
  rss: /feed.xml