# Site Configuration for TaskNix.com
name: TaskNix
description: Expert reviews of productivity tools, software, and services
avatar: https://tasknix.com/images/tasknix-logo.png  # Update with your actual logo URL

# Site URL configuration
url: "https://tasknix.com"  # Your production URL
baseurl: ""  # Leave empty unless using project GitHub Pages

# Content settings
permalink: /:title/
timezone: America/New_York  # Set your preferred timezone
future: false  # Don't publish posts with future dates

# SEO Optimization
title: TaskNix | Productivity Tools Reviews & Comparisons
keywords: "productivity tools, software reviews, task management, time tracking"
twitter_username: tasknix  # Update with your Twitter handle
github_username: tasknix  # Update with your GitHub org

# Social/Footer links
footer-links:
  twitter: tasknix
  github: tasknix/tasknix.github.io  # Update with your repo
  linkedin: company/tasknix  # Update with your LinkedIn
  rss: /feed.xml

# Analytics and Comments
google_analytics: UA-XXXXXX-X  # Replace with your GA tracking ID
disqus: tasknix  # Replace with your Disqus shortname

# Technical Configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# PLUGINS SECTION
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

# SEO TAG CONFIG (recommended)
jekyll-seo-tag:
  meta_tags: # Control what appears in meta tags
    - name: "twitter:card"
      value: "summary_large_image"
    - name: "og:image"
      value: "/assets/your-default-social-image.jpg"

# SITEMAP CONFIG (optional)
sitemap:
  lastmod: date # Adds last modified dates
  priority: 0.7 # Default priority
  changefreq: weekly

# PAGINATION CONFIG (for review lists)
pagination:
  enabled: true
  per_page: 10
  permalink: '/reviews/:num/'
  sort_field: 'date'
  sort_reverse: true

# FEED CONFIG (RSS/Atom)
feed:
  path: feed.xml
  limit: 20

# Sass processing
sass:
  style: :compressed  # Minified for production

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - .idea
  - .vscode

# TaskNix-specific configurations
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      affiliate_disclosure: true
      rating_system: true
      toc: true  # Table of contents

# Content categories matching your requirements
collections:
  productivity_tools:
    output: true
    permalink: /:collection/:name/
  categories:
    - project_management
    - note_taking
    - time_tracking
    - communication
    - file_sharing
    - automation
    - writing_software
    - scheduling_apps

# Version info
version: v1.0.0