# Site Configuration for TaskNix.com
name: TaskNix
description: Expert reviews of productivity tools, software, and services
avatar: https://tasknix.com/images/tasknix-logo.png  # Update with your actual logo URL

# Site URL configuration
url: "https://tasknix.com"  # Your production URL
baseurl: ""  # Leave empty unless using project GitHub Pages

# Content settings
permalink: /:title/
timezone: America/New_York  # Set your preferred timezone
future: false  # Don't publish posts with future dates

# SEO Optimization
title: TaskNix | Productivity Tools Reviews & Comparisons
keywords: "productivity tools, software reviews, task management, time tracking"
twitter_username: tasknix  # Update with your Twitter handle
github_username: tasknix  # Update with your GitHub org

# Social/Footer links
footer-links:
  twitter: tasknix
  github: tasknix/tasknix.github.io  # Update with your repo
  linkedin: company/tasknix  # Update with your LinkedIn
  rss: /feed.xml

# Analytics and Comments
google_analytics: UA-XXXXXX-X  # Replace with your GA tracking ID
disqus: tasknix  # Replace with your Disqus shortname

# Technical Configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # For better SEO handling

# Sass processing
sass:
  style: :compressed  # Minified for production

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - .idea
  - .vscode

# TaskNix-specific configurations
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      affiliate_disclosure: true
      rating_system: true
      toc: true  # Table of contents

# Content categories matching your requirements
collections:
  productivity_tools:
    output: true
    permalink: /:collection/:name/
  categories:
    - project_management
    - note_taking
    - time_tracking
    - communication
    - file_sharing
    - automation
    - writing_software
    - scheduling_apps

# Version info
version: v1.0.0