# Site Configuration for TaskNix.com
title: TaskNix
description: Expert productivity tool reviews and comparisons
baseurl: ""
url: "https://tasknix.com"

# Build settings
markdown: kramdown

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:title/

# Default layouts
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Include these files
include:
  - _pages
  - _posts
  - assets
  - images

# Files that can be removed (they're now in _pages):
# - writing_software.html (redirect file)
# - time_tracking.html (redirect file)
# - scheduling_apps.html (redirect file)
# - project_management.html (redirect file)
# - note_taking.html (redirect file)
# - file_sharing.html (redirect file)
# - ethics-policy.html (redirect file)
# - contact.html (redirect file)
# - comparisons.html (redirect file)
# - automation.html (redirect file)
# - about.html (redirect file)

# Permalinks
permalink: /:title/

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Fix for page globbing
keep_files:
  - .git
  - .svn

# Theme settings
theme: null # Disable default theme
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never