# Site Configuration for TaskNix.com
name: TaskNix
description: Expert reviews of productivity tools, software, and services
avatar: https://tasknix.com/images/tasknix-logo.png  # Update with your actual logo URL

# Site URL configuration
url: "https://tasknix.com"
baseurl: ""  # Leave empty unless using project GitHub Pages

# Content settings
permalink: /:title/
timezone: America/New_York
future: false

# SEO Optimization
title: TaskNix | Productivity Tools Reviews & Comparisons
keywords: "productivity tools, software reviews, task management, time tracking"
twitter_username: tasknix
github_username: tasknix

# Social/Footer links
footer-links:
  twitter: tasknix
  github: tasknix/tasknix.github.io
  linkedin: company/tasknix
  rss: /feed.xml

# Analytics and Comments
google_analytics: UA-XXXXXX-X
disqus: tasknix

# Technical Configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins (GitHub Pages supported only)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# SEO TAG CONFIG (recommended)
jekyll-seo-tag:
  meta_tags:
    - name: "twitter:card"
      value: "summary_large_image"
    - property: "og:image"
      content: "/assets/your-default-social-image.jpg"

# SITEMAP CONFIG (optional)
sitemap:
  lastmod: date
  priority: 0.7
  changefreq: weekly

# FEED CONFIG (RSS/Atom)
feed:
  path: feed.xml
  limit: 20

# Sass processing (consolidated)
sass:
  style: compressed
  load_paths:
    - _sass

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - .idea
  - .vscode

# TaskNix-specific configurations
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: "/:title/"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      affiliate_disclosure: true
      rating_system: true
      toc: true

# Content categories (standardized for Jekyll)
categories:
  - project_management
  - note_taking
  - time_tracking
  - communication
  - file_sharing
  - automation
  - writing_software
  - scheduling_apps

# Collections (GitHub Pages compatible)
collections:
  productivity_tools:
    output: true
    permalink: /:collection/:name/

# Enable custom styles (ensure file exists)
minima:
  include_css:
    - /assets/css/custom.css

# Version info
version: v1.0.0

# Header navigation configuration
header_pages:
  - about.md
  - reviews.html
  - comparisons.md
  - categories.md
  - contact.md